/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PKPPermissions } from "./PKPPermissions";
export * as factories from "./factories";
export { PKPPermissions__factory } from "./factories/PKPPermissions__factory";
