/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface PKPHelperInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "mintNextAndAddAuthMethods"
      | "mintNextAndAddAuthMethodsWithTypes"
      | "onERC721Received"
      | "owner"
      | "pkpNFT"
      | "pkpPermissions"
      | "renounceOwnership"
      | "setPkpNftAddress"
      | "setPkpPermissionsAddress"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;

  encodeFunctionData(
    functionFragment: "mintNextAndAddAuthMethods",
    values: [
      BigNumberish,
      BigNumberish[],
      BytesLike[],
      BytesLike[],
      BigNumberish[][],
      boolean,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "mintNextAndAddAuthMethodsWithTypes",
    values: [
      BigNumberish,
      BytesLike[],
      BigNumberish[][],
      AddressLike[],
      BigNumberish[][],
      BigNumberish[],
      BytesLike[],
      BytesLike[],
      BigNumberish[][],
      boolean,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pkpNFT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pkpPermissions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPkpNftAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPkpPermissionsAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "mintNextAndAddAuthMethods",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintNextAndAddAuthMethodsWithTypes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pkpNFT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pkpPermissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPkpNftAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPkpPermissionsAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PKPHelper extends BaseContract {
  connect(runner?: ContractRunner | null): PKPHelper;
  waitForDeployment(): Promise<this>;

  interface: PKPHelperInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  mintNextAndAddAuthMethods: TypedContractMethod<
    [
      keyType: BigNumberish,
      permittedAuthMethodTypes: BigNumberish[],
      permittedAuthMethodIds: BytesLike[],
      permittedAuthMethodPubkeys: BytesLike[],
      permittedAuthMethodScopes: BigNumberish[][],
      addPkpEthAddressAsPermittedAddress: boolean,
      sendPkpToItself: boolean
    ],
    [bigint],
    "payable"
  >;

  mintNextAndAddAuthMethodsWithTypes: TypedContractMethod<
    [
      keyType: BigNumberish,
      permittedIpfsCIDs: BytesLike[],
      permittedIpfsCIDScopes: BigNumberish[][],
      permittedAddresses: AddressLike[],
      permittedAddressScopes: BigNumberish[][],
      permittedAuthMethodTypes: BigNumberish[],
      permittedAuthMethodIds: BytesLike[],
      permittedAuthMethodPubkeys: BytesLike[],
      permittedAuthMethodScopes: BigNumberish[][],
      addPkpEthAddressAsPermittedAddress: boolean,
      sendPkpToItself: boolean
    ],
    [bigint],
    "payable"
  >;

  onERC721Received: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [string],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pkpNFT: TypedContractMethod<[], [string], "view">;

  pkpPermissions: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setPkpNftAddress: TypedContractMethod<
    [newPkpNftAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  setPkpPermissionsAddress: TypedContractMethod<
    [newPkpPermissionsAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "mintNextAndAddAuthMethods"
  ): TypedContractMethod<
    [
      keyType: BigNumberish,
      permittedAuthMethodTypes: BigNumberish[],
      permittedAuthMethodIds: BytesLike[],
      permittedAuthMethodPubkeys: BytesLike[],
      permittedAuthMethodScopes: BigNumberish[][],
      addPkpEthAddressAsPermittedAddress: boolean,
      sendPkpToItself: boolean
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "mintNextAndAddAuthMethodsWithTypes"
  ): TypedContractMethod<
    [
      keyType: BigNumberish,
      permittedIpfsCIDs: BytesLike[],
      permittedIpfsCIDScopes: BigNumberish[][],
      permittedAddresses: AddressLike[],
      permittedAddressScopes: BigNumberish[][],
      permittedAuthMethodTypes: BigNumberish[],
      permittedAuthMethodIds: BytesLike[],
      permittedAuthMethodPubkeys: BytesLike[],
      permittedAuthMethodScopes: BigNumberish[][],
      addPkpEthAddressAsPermittedAddress: boolean,
      sendPkpToItself: boolean
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "onERC721Received"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pkpNFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pkpPermissions"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPkpNftAddress"
  ): TypedContractMethod<[newPkpNftAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPkpPermissionsAddress"
  ): TypedContractMethod<
    [newPkpPermissionsAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
